### ISSUE TITLE
Razorpay Checkout Script Conflict Page CSS Styles

### ISSUE THREAD

**Issue by mastersandeep92** [tiltbike/razorpay-checkout-js#54]
**Describe the bug**
Razorpay Checkout Script Conflict Page CSS Styles After the RazorPay Payment Popup is Opened in Nextjs webSite. Please Watch the Video

**Expected behavior**
Razorpay Checkout Script Conflict Page CSS Styles After the RazorPay Payment Popup is Opened in Nextjs webSite. Please Watch the Video

**Screenshots**
<img width="1148" alt="Screen Shot 2022-09-26 at 12 13 57 PM" src="https://user-images.githubusercontent.com/107744866/192211535-0844ed52-c18a-4e3b-9fd8-cb7d52076f87.png">
<img width="1148" alt="Screen Shot 2022-09-26 at 12 14 35 PM" src="https://user-images.githubusercontent.com/107744866/192211591-7e7f6077-eb6e-4991-a035-c55b7b24987d.png">
<img width="1148" alt="Screen Shot 2022-09-26 at 12 14 57 PM" src="https://user-images.githubusercontent.com/107744866/192211624-39e54d51-35f0-493d-b408-875eda3d6b3a.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Browser Chrome
 - Version 105.0.5195.125

**Additional context**
[screen-capture.webm](https://user-images.githubusercontent.com/107744866/192094919-17a7efe1-2466-4a38-bf5a-62146eccbcdc.webm)

**Comment by prabhupadhayay** [comment]
I am getting the same issue while integrating in react.js .
@mastersandeep92 have you find any solution yet ?

**Comment by shadygill** [comment]
@dakshshah96 ! I am also encountering this issue ! Can you look into it ?

**Comment by prabhupadhayay** [comment]
@dakshshah96 ! any update on this issue ?

**Comment by mastersandeep92** [comment]
@dakshshah96 !! have you find any update on this Issue ? I am Struggle with this issue more than 3 days in Production mode
